apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmi-calculator
  template:
    metadata:
      labels:
        app: bmi-calculator
    spec:
      containers:
        - name: bmi-calculator
          image: adeel48180/bmi_cal:latest 
          ports:
            - containerPort: 5007
apiVersion: v1
kind: Service
metadata:
  name: bmi-calculator-service
spec:
  selector:
    app: bmi-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer